### ISSUE TITLE
Could use Floating point encoding

### ISSUE THREAD

**Issue by hardbyte** [Georeactor/encrypted-geofence#5]
Hey nice project! I'm glad to see my Paillier implementations being used :-)

I just read a comment in your [second notebook](https://github.com/Georeactor/encrypted-geofence/blob/master/notebooks/2)%20Making%20a%20Server%20for%20Homomorphic%20Encryption.ipynb):
```
# Paillier cryptosystem seems to works only on positive integers, so we cannot
# use -180.00 to +180.00 coordinates.
```

This is true of the underlying cryptosystem, but python-paillier does support encoding floating point numbers see the [usage docs](https://python-paillier.readthedocs.io/en/develop/usage.html). However note I didn't port that encoding to https://github.com/hardbyte/paillier.js

**Comment by mapmeld** [comment]
That's good to know! I will plan reword this, but I am reluctant to change the multiplication here because I want my notebook to be consistent with how the server works

While you're here, have you looked at the new Microsoft SEAL library for homomorphic encryption? I was tempted to use emscripten or node-gyp to JS-ify it, but I have never made a module this way before.

**Comment by hardbyte** [comment]
Fair enough! I imagine you could add the encoding to the JS library without too much drama.

I've been watching SEAL for a while - and am very happy that they have properly open sourced it. Haven't used it in anger though, and can only wish you luck with the ambitious plan of js-ification!
